package skuc.io;

import skuc.io.skuciocore.models.events.device.ValueReceived;
import skuc.io.skuciocore.models.events.device.StatusReceived;
import skuc.io.skuciocore.models.csm.StateRegistry;
import skuc.io.skuciocore.models.csm.configuration.Context;
import skuc.io.skuciocore.services.StateRegistryService;

global StateRegistryService stateRegistryService;

rule "Update Value State"
  no-loop
  salience 110
  when
    ValueReceived($deviceType: deviceType, $value: value)
    $reg : StateRegistry()
  then
    modify($reg) {
      setState("value_" + $deviceType, $value + "");
    }
    stateRegistryService.update($reg);
end;

rule "Update Status State"
  no-loop
  salience -100
  when
    $sr: StatusReceived($deviceType: deviceType, $value: value)
    $reg : StateRegistry()
  then
    delete($sr)
    modify($reg) {
      setState($deviceType, $value);
    }
    stateRegistryService.update($reg);
end;