package skuc.io;

import skuc.io.skuciocore.models.events.device.ValueReceived;
import skuc.io.skuciocore.models.events.device.StatusReceived;
import skuc.io.skuciocore.models.csm.StateRegistry;
import skuc.io.skuciocore.models.csm.configuration.Context;
import skuc.io.skuciocore.services.StateRegistryService;

global StateRegistryService stateRegistryService;

rule "Print context"
  when 
    $c: Context()
  then
    System.out.println($c.getName());
end;

rule "Update Status State"
  no-loop
  salience -100
  when
    StatusReceived($deviceType: deviceType, $value: value)
    $reg : StateRegistry()
  then
    modify($reg) {
      setState($deviceType, $value);
    }
    stateRegistryService.update($reg);
end;