package skuc.io;

import skuc.io.skuciocore.models.events.kjar.ValueReceivedCopy;
import skuc.io.skuciocore.models.events.device.StatusReceived;
import skuc.io.skuciocore.models.csm.StateRegistry;
import skuc.io.skuciocore.models.csm.configuration.Context;
import skuc.io.skuciocore.services.StateRegistryService;

global StateRegistryService stateRegistryService;

rule "Update Value State"
  salience -100
  when
    $vr : ValueReceivedCopy($deviceType: deviceType, $value: value)
    $reg : StateRegistry()
  then
    delete($vr);
    modify($reg) {
      setState("value_" + $deviceType, $value + "");
    }
    stateRegistryService.update($reg);
end;

rule "Update Status State"
  salience -100
  when
    $sr: StatusReceived($deviceType: deviceType, $value: value)
    $reg : StateRegistry()
  then
    delete($sr)
    modify($reg) {
      setState($deviceType, $value);
    }
    stateRegistryService.update($reg);
end;