export const ADD_TIME_PERIOD_ACTIVATION = 'ADD_TIME_PERIOD_ACTIVATION';
export const UPDATE_TIME_PERIOD_ACTIVATION = 'UPDATE_TIME_PERIOD_ACTIVATION';
export const DELETE_TIME_PERIOD_ACTIVATION = 'DELETE_TIME_PERIOD_ACTIVATION';